name: xArm
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - termcolor
    - gym==0.19.0
    - mujoco-py
    - pandas
    - wandb
    - moviepy
    - imageio
    - opencv-python